def pathTA(ta):
    getpath = {
        'volume_adi': 'Accumulation/Distribution Index (ADI)',
        'volume_obv': 'On-balance volume (OBV)',
        'volume_cmf': 'Chaikin Money Flow (CMF)',
        'volume_fi': 'Force Index (FI)',
        'volume_mfi': 'Money Flow Index (MFI)',
        'volume_em': 'Ease of movement (EoM, EMV)', 
        'volume_sma_em': 'Signal Ease of movement (EoM, EMV)', 
        'volume_vpt': 'Volume-price trend (VPT)', 
        'volume_nvi': 'Negative Volume Index (NVI)',
        'volume_vwap': 'Volume Weighted Average Price (VWAP)', 
        'volatility_atr': 'Average True Range (ATR)', 
        'volatility_bbm': 'Bollinger Channel Middle Band', 
        'volatility_bbh': 'Bollinger Channel High Band',
        'volatility_bbl': 'Bollinger Channel Low Band', 
        'volatility_bbw': 'Bollinger Channel Band Width', 
        'volatility_bbp': 'Bollinger Channel Percentage Band', 
        'volatility_bbhi': 'Bollinger Channel Indicator Crossing High Band',
        'volatility_bbli': 'Bollinger Channel Indicator Crossing Low Band', 
        'volatility_kcc': 'Keltner Channels (KC)', 
        'volatility_kch': 'Keltner Channel High Band', 
        'volatility_kcl': 'Keltner Channel Low Band',
        'volatility_kcw': 'Keltner Channel Band Width', 
        'volatility_kcp': 'Keltner Channel Percentage Band', 
        'volatility_kchi': 'Keltner Channel Indicator Crossing High Band',
        'volatility_kcli': 'Keltner Channel Indicator Crossing Low Band', 
        'volatility_dcl': 'Donchian Channel Low Band', 
        'volatility_dch': 'Donchian Channel High Band', 
        'volatility_dcm': 'Donchian Channel Middle Band',
        'volatility_dcw': 'Donchian Channel Band Width', 
        'volatility_dcp': 'Donchian Channel Percentage Band', 
        'volatility_ui': 'Ulcer Index', 
        'trend_macd': 'Moving Average Convergence Divergence (MACD)',
        'trend_macd_signal': 'MACD Signal Line', 
        'trend_macd_diff': 'MACD Histogram', 
        'trend_sma_fast': 'Simple Moving Average (SMA)',
        'trend_sma_slow': 'Simple Moving Average (SMA)', 
        'trend_ema_fast': 'Exponential Moving Average (EMA)', 
        'trend_ema_slow': 'Exponential Moving Average (EMA)', 
        'trend_adx': 'Average Directional Index (ADX)',
        'trend_adx_pos': 'Plus Directional Indicator (+DI)', 
        'trend_adx_neg': 'Minus Directional Indicator (-DI)', 
        'trend_vortex_ind_pos': 'Plus Vortex Indicator (+VI)',
        'trend_vortex_ind_neg': 'Negative Vortex Indicator (-VI)', 
        'trend_vortex_ind_diff': 'Diff Vortex Indicator (Diff VI)', 
        'trend_trix': 'Trix (TRIX)',
        'trend_mass_index': 'Mass Index (MI)', 
        'trend_cci': 'Commodity Channel Index (CCI)', 
        'trend_dpo': 'Detrended Price Oscillator (DPO)', 
        'trend_kst': 'KST Oscillator (KST Signal)',
        'trend_kst_sig': 'Signal Line Know Sure Thing (KST)', 
        'trend_kst_diff': 'Diff Know Sure Thing (KST)', 
        'trend_ichimoku_conv': 'Tenkan-sen (Conversion Line)',
        'trend_ichimoku_base': 'Kijun-sen (Base Line)', 
        'trend_ichimoku_a': 'Senkou Span A (Leading Span A)', 
        'trend_ichimoku_b': 'Senkou Span B (Leading Span B)',
        'trend_visual_ichimoku_a': 'Visual Ichimoku A', 
        'trend_visual_ichimoku_b': 'Visual Ichimoku B', 
        'trend_aroon_up': 'Aroon Down Channel',
        'trend_aroon_down': 'Aroon Down Channel', 
        'trend_aroon_ind': 'Aroon Indicator', 
        'trend_psar_up': 'PSAR up trend value',
        'trend_psar_down': 'PSAR down trend value', 
        'trend_psar_up_indicator': 'PSAR up trend value indicator',
        'trend_psar_down_indicator': 'PSAR down trend value indicator', 
        'trend_stc': 'Schaff Trend Cycle (STC)', 
        'momentum_rsi': 'Relative Strength Index (RSI)',
        'momentum_stoch_rsi': 'Stochastic RSI', 
        'momentum_stoch_rsi_k': 'Stochastic RSI %k', 
        'momentum_stoch_rsi_d': 'Stochastic RSI %d',
        'momentum_tsi': 'True strength index (TSI)', 
        'momentum_uo': 'Ultimate Oscillator', 
        'momentum_stoch': 'Stochastic Oscillator',
        'momentum_stoch_signal': 'Signal Stochastic Oscillator', 
        'momentum_wr': '•	Williams %R', 
        'momentum_ao': 'Awesome Oscillator (AO)', 
        'momentum_kama': 'Kaufman’s Adaptive Moving Average (KAMA)',
        'momentum_roc': 'Rate of Change (ROC)', 
        'momentum_ppo': 'Percentage Price Oscillator (PPO)', 
        'momentum_ppo_signal': 'Percentage Price Oscillator Histogram',
        'momentum_ppo_hist': 'Percentage Price Oscillator Signal Line', 
        'others_dr': 'Daily Return (DR)', 
        'others_dlr': 'Daily Log Return (DLR)', 
        'others_cr': 'Cumulative Return (CR)'
        }
    return getpath[ta]